### ISSUE TITLE
reproducing experiment for wiredtiger

### ISSUE THREAD

**Issue by pohaoc** [uclasystem/midas#1]
Hi,

In the WiredTiger folder's README, it's mentioned that there is a `run/run.sh`. However, I couldn't find it in the current repository. 
Can you point me to where that is?

Thanks!

**Comment by ivanium** [comment]
Thank you for your interest in Midas! I have pushed the missing scripts to the repo. Please find it at `apps/wiredtiger/run`.

Thank you!

**Comment by pohaoc** [comment]
Thanks! Closing this issue.
