### ISSUE TITLE
Reproduce the app OneRF(SocialNet)

### ISSUE THREAD

**Issue by chenzq-98** [uclasystem/midas#4]
Fail to get the tracegen/trace.json mentioned in the apps/OneRF/inc/requestor.hpp:51. How to get it?

**Comment by ivanium** [comment]
Hi @czq693497091,

Thank you for your interest in Midas. We recently updated the Midas codebase to include the ported SocialNet codebase. You can find [detailed instructions here](https://github.com/uclasystem/midas/tree/main/apps/DeathStarBench/socialNetwork).

To answer your original question: OneRF was initially ported from [RobinHood](https://github.com/dasebe/robinhoodcache) and will not be maintained further in Midas. You can refer to the RobinHood repo’s README for steps on generating the trace files you need.

Hope this helps, and feel free to reach out with any other questions.

**Comment by chenzq-98** [comment]
> Hi @czq693497091,
> 
> Thank you for your interest in Midas. We recently updated the Midas codebase to include the ported SocialNet codebase. You can find [detailed instructions here](https://github.com/uclasystem/midas/tree/main/apps/DeathStarBench/socialNetwork).
> 
> To answer your original question: OneRF was initially ported from [RobinHood](https://github.com/dasebe/robinhoodcache) and will not be maintained further in Midas. You can refer to the RobinHood repo’s README for steps on generating the trace files you need.
> 
> Hope this helps, and feel free to reach out with any other questions.

Thanks for your patient answer and I have solved the problem.
